menu:
  Home: /
  About: /about
  Projects: /projects
  Archives: /archives

widgets:
- category
- tag
- box

box:
  github: https://github.com/samertm
  twitter: https://twitter.com/samertm
  samer@samertm.com: "mailto:samer@samertm.com"
  resume: /res/samermastersonresume.pdf

Excerpt_link: Read More

twitter:
  username: samertm
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  twitter: true

fancybox: true

google_analytics: UA-38302865-2
rss: /atom.xml
